apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
      - name: nginx
        image: A40820AB5DE324D5FA6F1035631ABFB0-1925417406.US-EAST-1.ELB.AMAZONAWS.COM/HARBOR_PROJECT/app:build-6
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: gitops-demo-config
