apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      imagePullSecrets:
      - name: harbor-registry
      containers:
      - name: nginx
        image: ASDa40820ab5de324d5fa6f1035631abfb0-1925417406.us-east-1.elb.amazonaws.com/student06/app:build-
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: gitops-demo-config
